ALL: server client read write
server: server.cpp
	g++ server.cpp -o server -lrt
client: client.cpp
	g++ client.cpp -o client 
read: read.cpp
	g++ read.cpp -o read -lrt
write: write.cpp
	g++ write.cpp -o write -lrt

