ALL: CGIserver client1 client2 client3
CGIserver: CGIserver.cpp
	g++ -g CGIserver.cpp -o CGIserver
client1: client1.cpp
	g++ -g client1.cpp -o client1
client2: client2.cpp
	g++ -g client2.cpp -o client2
client3: client3.cpp
	g++ -g client3.cpp -o client3